<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\URL;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Schema::defaultStringLength(200);   
        
        // Fix for "The information you're about to submit is not secure" on Vercel
        // Force HTTPS for all routes/assets generated by Laravel in production
        if (config('app.env') === 'production' || str_contains(request()->url(), 'vercel.app')) {
            URL::forceScheme('https');
        }
    }
}
